'use client'

import type { Metadata } from "next";
import {useState} from 'react';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar'
import MovieList from '@/components/MovieList';
import Home from '@/app/page';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [movieSearch, setMovieSearch] = useState<string>('');

  function setNewMovieName(name: string): void {
    setMovieSearch(name);
  }
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar 
        setNewMovieName={setNewMovieName}
        />
        <Home 
        movieSearch={movieSearch}
        />
        {/* <MovieList /> */}
        {/* {children} */}
      </body>
    </html>
  );
}